import type { Experience } from "@/types/portfolio";

export const experienceOverview = {
  heading: "Working across data, analytics, and software.",
  introduction:
    "Hands-on experience building data pipelines, backend systems, analytics products, automation workflows, and applied machine-learning solutions.",
} as const;

export const experiences: readonly Experience[] = [
  {
    id: "stratpoint-technologies",
    title: "Data Engineer Intern",
    company: "Stratpoint Technologies",
    category: "Internship",
    range: { start: "2026-06-01", end: "2026-08-31" },
    displayDate: "Jun–Aug 2026",
    highlights: [
      "Built end-to-end batch pipelines for ecommerce and movie analytics, working with datasets from 90K+ movie records to 1.55M source rows.",
      "Designed dimensional warehouse layers across staging, intermediate, and marts.",
      "Implemented tests for grain, referential integrity, source preservation, and reconciliation.",
      "Translated business requirements into KPIs and dashboards, including a partner-screening solution that narrowed 44,940 companies by 83.6%.",
    ],
    skills: [
      "Python",
      "PySpark",
      "PostgreSQL",
      "dbt",
      "Apache Airflow",
      "Docker",
    ],
  },
  {
    id: "dost-sei",
    title: "Backend Developer Intern",
    company:
      "Department of Science and Technology – Science Education Institute",
    category: "Internship",
    range: { start: "2026-01-01", end: "2026-03-31" },
    displayDate: "Jan–Mar 2026",
    highlights: [
      "Developed backend business logic, REST APIs, and database integrations for microservices.",
      "Tested services with Jest and Postman while collaborating in an Agile team.",
    ],
    skills: ["Node.js", "TypeScript", "PostgreSQL", "REST APIs", "Jest"],
  },
  {
    id: "edufied",
    title: "Software Engineer (Automation) Intern",
    company: "Edufied",
    category: "Internship",
    range: { start: "2025-10-01", end: "2026-01-31" },
    displayDate: "Oct 2025–Jan 2026",
    highlights: [
      "Built Python and Playwright automation for web scraping, data cleaning, and MongoDB-backed workflows.",
      "Increased job data extraction volume by 40%.",
    ],
    skills: ["Python", "Playwright", "MongoDB", "Web Scraping"],
  },
  {
    id: "lamina-studios",
    title: "Data Science Intern",
    company: "Lamina Studios, LLC",
    category: "Internship",
    range: { start: "2025-07-01", end: "2025-08-31" },
    displayDate: "Jul–Aug 2025",
    location: "Remote – Washington, United States",
    logo: "/images/experience-logos/lamina-logo.png",
    highlights: [
      "Built analytics features for operations, warehouse, fleet, RFID activity, and live GPS data.",
      "Developed and integrated REST API-backed services across Flask, MySQL, Next.js, PostgreSQL, and Redis.",
    ],
    skills: [
      "Python",
      "Flask",
      "MySQL",
      "Next.js",
      "PostgreSQL",
      "Redis",
      "REST APIs",
    ],
  },
  {
    id: "nidec-control-techniques",
    title: "Data Science Intern",
    company: "NIDEC Control Techniques",
    category: "Internship",
    range: { start: "2023-11-01", end: "2024-03-31" },
    displayDate: "Nov 2023–Mar 2024",
    location: "Remote – Nonthaburi, Thailand",
    logo: "/images/experience-logos/nidec-logo.png",
    highlights: [
      "Built a Python, Streamlit, and MySQL admin dashboard with data-validation workflows.",
      "Reduced detected data errors by 25%.",
    ],
    skills: ["Python", "Streamlit", "MySQL", "Data Validation"],
  },
  {
    id: "gdsc-data-co-lead",
    title: "Data Co-Lead",
    company: "Google Developer Student Clubs – PUP Main",
    category: "Volunteering",
    range: { start: "2023-09-01", end: "2024-06-30" },
    displayDate: "Sep 2023–Jun 2024",
    location: "Manila, Philippines",
    logo: "/images/experience-logos/gdsc-logo.png",
    highlights: [
      "Co-led the data track for 50+ members, helping design the learning roadmap, assessments, and onboarding activities.",
      "Led a data-engineering roadmap session and mentored members.",
    ],
    skills: ["Data Engineering", "Mentoring", "Learning Design"],
  },
  {
    id: "facts-on-the-ground",
    title: "Lead Machine Learning Engineer",
    company: "Facts on the Ground",
    category: "Volunteering",
    range: { start: "2023-02-01", end: "2023-08-31" },
    displayDate: "Feb–Aug 2023",
    location: "Remote – Philippines",
    logo: "/images/experience-logos/gdsc-logo.png",
    highlights: [
      "Led a 7-member ML sub-team and coordinated preprocessing and validation work that reduced irrelevant data by 20.2%.",
      "Supported text preprocessing with data cleaning, tokenization, and normalization.",
    ],
    skills: ["Python", "Data Cleaning", "pandas", "NLTK", "Git"],
  },
  {
    id: "omdena-berlin",
    title: "Junior Machine Learning Engineer",
    company: "Omdena – Berlin Chapter",
    category: "Volunteering",
    range: { start: "2023-08-01", end: "2023-10-31" },
    displayDate: "Aug–Oct 2023",
    location: "Remote – Berlin, Germany",
    logo: "/images/experience-logos/omdena-logo.png",
    highlights: [
      "Collaborated on a waste-management optimization project, contributing EDA, a Streamlit application, and task deployment/presentation.",
      "Conducted exploratory analysis and helped build a Streamlit application.",
    ],
    skills: ["Python", "EDA", "pandas", "Streamlit", "Git"],
  },
  {
    id: "gdsc-data-ai-cadet",
    title: "Junior Data & AI Cadet",
    company: "Google Developer Student Clubs – PUP Main",
    category: "Volunteering",
    range: { start: "2022-10-01", end: "2023-08-31" },
    displayDate: "Oct 2022–Aug 2023",
    location: "Manila, Philippines",
    logo: "/images/experience-logos/gdsc-logo.png",
    highlights: [
      "Participated in structured Data & AI training, technical activities, and community learning initiatives.",
    ],
    skills: ["Data", "Artificial Intelligence"],
  },
] as const;
