import type { Experience } from "@/types/portfolio";

export const experiences = [
  {
    id: "lamina-studios",
    title: "Data Science Intern",
    company: "Lamina Studios, LLC",
    category: "Internship",
    range: { start: "2025-07-01", end: "2025-08-31" },
    displayDate: "July – August 2025",
    location: "Remote – Washington, United States",
    logo: "/images/experience-logos/lamina-logo.png",
    highlights: [
      "Completed a five-week data science immersion covering Python, data preprocessing, and model evaluation.",
      "Performed exploratory analysis on logistics datasets and built interactive visualizations with Plotly.js and Metabase.",
      "Built and integrated a full-stack analytics dashboard into a smart logistics platform.",
      "Containerized services with Docker and deployed the multi-service application to Render, Railway, and Vercel.",
    ],
    skills: [
      "Python",
      "Laravel",
      "Next.js",
      "PostgreSQL",
      "EDA",
      "Metabase",
      "Docker",
      "Git",
    ],
  },
  {
    id: "nidec-control-techniques",
    title: "Data Science Intern",
    company: "NIDEC Control Techniques",
    category: "Internship",
    range: { start: "2023-11-01", end: "2024-05-31" },
    displayDate: "November 2023 – May 2024",
    location: "Remote – Nonthaburi, Thailand",
    logo: "/images/experience-logos/nidec-logo.png",
    highlights: [
      "Collaborated with co-interns to apply software development practices and consistently meet deadlines.",
      "Helped prototype an itinerary system with Python, Streamlit, and MySQL and gathered requirements for its proposal.",
      "Collected, cleaned, and compiled marketing data while supporting the marketing team's analysis.",
    ],
    skills: ["Python", "Streamlit", "MySQL", "Spreadsheets", "Git"],
  },
  {
    id: "omdena-berlin",
    title: "Junior Machine Learning Engineer",
    company: "Omdena – Berlin Chapter",
    category: "Volunteering",
    range: { start: "2023-08-01", end: "2023-10-31" },
    displayDate: "August – October 2023",
    location: "Remote – Berlin, Germany",
    logo: "/images/experience-logos/omdena-logo.png",
    highlights: [
      "Collaborated with 38 professionals on an end-to-end waste-management optimization project.",
      "Conducted exploratory data analysis and created Python visualizations.",
      "Led development of the Waste Optimization Management web application with Streamlit.",
    ],
    skills: ["Python", "EDA", "Pandas", "Streamlit", "Git"],
  },
  {
    id: "facts-on-the-ground",
    title: "Lead Machine Learning Engineer",
    company: "Facts on the Ground & GDSC – PUP Main",
    category: "Volunteering",
    range: { start: "2023-02-01", end: "2023-08-31" },
    displayDate: "February – August 2023",
    location: "Remote – Philippines",
    logo: "/images/experience-logos/gdsc-logo.png",
    highlights: [
      "Worked with 38 collaborators on Detecting Facts on the Ground Using Machine Learning.",
      "Led a seven-person data-wrangling and validation team, reducing irrelevant and garbage data by 20.2%.",
      "Assisted with tokenization and normalization using NLTK.",
    ],
    skills: ["Python", "Data Cleaning", "Pandas", "NLTK", "Git"],
  },
] as const satisfies readonly Experience[];
