import type { Experience } from "@/types/portfolio";

export const experiences: readonly Experience[] = [
  {
    id: "stratpoint-technologies",
    title: "Data Engineer Intern",
    company: "Stratpoint Technologies",
    category: "Internship",
    range: { start: "2026-06-01", end: "2026-08-31" },
    displayDate: "June – August 2026",
    highlights: [
      "Built end-to-end batch pipelines for ecommerce and movie analytics, working with datasets from 90K+ movie records to 1.55M source rows.",
      "Designed dimensional warehouse layers across staging, intermediate, and marts.",
      "Implemented tests for grain, referential integrity, source preservation, and reconciliation.",
      "Translated business requirements into KPIs and dashboards, including a partner-screening solution that narrowed 44,940 companies by 83.6%.",
    ],
    skills: [
      "Python",
      "PySpark",
      "PostgreSQL",
      "dbt",
      "Apache Airflow",
      "Docker",
    ],
  },
  {
    id: "dost-sei",
    title: "Backend Developer Intern",
    company:
      "Department of Science and Technology – Science Education Institute",
    category: "Internship",
    range: { start: "2026-01-01", end: "2026-03-31" },
    displayDate: "January – March 2026",
    highlights: [
      "Developed backend business logic, REST APIs, and database integrations for microservices.",
      "Tested services with Jest and Postman while collaborating in an Agile team.",
    ],
    skills: ["Node.js", "TypeScript", "PostgreSQL", "REST APIs", "Jest"],
  },
  {
    id: "edufied",
    title: "Software Engineer (Automation) Intern",
    company: "Edufied",
    category: "Internship",
    range: { start: "2025-10-01", end: "2026-01-31" },
    displayDate: "October 2025 – January 2026",
    highlights: [
      "Built Python and Playwright automation for web scraping, data cleaning, and MongoDB-backed workflows.",
      "Increased job data extraction volume by 40%.",
    ],
    skills: ["Python", "Playwright", "MongoDB", "Web Scraping"],
  },
  {
    id: "lamina-studios",
    title: "Data Science Intern",
    company: "Lamina Studios, LLC",
    category: "Internship",
    range: { start: "2025-07-01", end: "2025-08-31" },
    displayDate: "July – August 2025",
    location: "Remote – Washington, United States",
    logo: "/images/experience-logos/lamina-logo.png",
    highlights: [
      "Built analytics features for operations, warehouse, fleet, RFID activity, and live GPS data.",
      "Developed and integrated REST API-backed services across Flask, MySQL, Next.js, PostgreSQL, and Redis.",
    ],
    skills: [
      "Python",
      "Flask",
      "MySQL",
      "Next.js",
      "PostgreSQL",
      "Redis",
      "REST APIs",
    ],
  },
  {
    id: "nidec-control-techniques",
    title: "Data Science Intern",
    company: "NIDEC Control Techniques",
    category: "Internship",
    range: { start: "2023-11-01", end: "2024-03-31" },
    displayDate: "November 2023 – March 2024",
    location: "Remote – Nonthaburi, Thailand",
    logo: "/images/experience-logos/nidec-logo.png",
    highlights: [
      "Built a Python, Streamlit, and MySQL admin dashboard with data-validation workflows.",
      "Reduced detected data errors by 25%.",
    ],
    skills: ["Python", "Streamlit", "MySQL", "Data Validation"],
  },
  {
    id: "gdsc-data-co-lead",
    title: "Data Co-Lead",
    company: "Google Developer Student Clubs – PUP Main",
    category: "Volunteering",
    range: { start: "2023-09-01", end: "2024-06-30" },
    displayDate: "September 2023 – June 2024",
    location: "Manila, Philippines",
    logo: "/images/experience-logos/gdsc-logo.png",
    highlights: [
      "Co-led the data track for 50+ members, designing assessments and the learning roadmap.",
      "Led a data-engineering roadmap session and mentored members.",
    ],
    skills: ["Data Engineering", "Mentoring", "Learning Design"],
  },
  {
    id: "omdena-berlin",
    title: "Junior Machine Learning Engineer",
    company: "Omdena – Berlin Chapter",
    category: "Volunteering",
    range: { start: "2023-08-01", end: "2023-10-31" },
    displayDate: "August – October 2023",
    location: "Remote – Berlin, Germany",
    logo: "/images/experience-logos/omdena-logo.png",
    highlights: [
      "Collaborated on an end-to-end waste-management optimization project.",
      "Conducted exploratory analysis and helped build a Streamlit application.",
    ],
    skills: ["Python", "EDA", "pandas", "Streamlit", "Git"],
  },
  {
    id: "facts-on-the-ground",
    title: "Lead Machine Learning Engineer",
    company: "Facts on the Ground – GDSC PUP Main",
    category: "Volunteering",
    range: { start: "2023-02-01", end: "2023-08-31" },
    displayDate: "February – August 2023",
    location: "Remote – Philippines",
    logo: "/images/experience-logos/gdsc-logo.png",
    highlights: [
      "Led a seven-person data-wrangling and validation team for a collaborative machine-learning project.",
      "Supported text preprocessing with data cleaning, tokenization, and normalization.",
    ],
    skills: ["Python", "Data Cleaning", "pandas", "NLTK", "Git"],
  },
  {
    id: "gdsc-data-ai-cadet",
    title: "Junior Data and AI Cadet",
    company: "Google Developer Student Clubs – PUP Main",
    category: "Volunteering",
    range: { start: "2022-10-01", end: "2023-08-31" },
    displayDate: "October 2022 – August 2023",
    location: "Manila, Philippines",
    logo: "/images/experience-logos/gdsc-logo.png",
    highlights: [],
    skills: ["Data", "Artificial Intelligence"],
  },
] as const;
