import type { SkillGroup } from "@/types/portfolio";

export const skillGroups = [
  {
    id: "data-engineering-analytics",
    title: "Data Engineering & Analytics",
    skills: [
      "ETL/ELT",
      "Data Pipelines",
      "Data Integration",
      "Data Warehousing",
      "Relational Data Modeling",
      "Dimensional Modeling",
      "Data Cleaning & Validation",
      "Data Quality",
      "Exploratory Data Analysis",
      "Web Scraping",
      "Data Visualization",
    ],
  },
  {
    id: "languages-data",
    title: "Languages & Data",
    skills: [
      "Python",
      "SQL",
      "PySpark",
      "pandas",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
    ],
  },
  {
    id: "tools-platforms",
    title: "Tools & Platforms",
    skills: [
      "dbt",
      "Apache Airflow",
      "Power BI",
      "Docker",
      "Supabase",
      "Microsoft Azure",
      "Git",
      "GitHub",
      "Microsoft Excel",
    ],
  },
  {
    id: "software-development",
    title: "Software Development",
    skills: [
      "TypeScript",
      "Node.js",
      "REST APIs",
      "FastAPI",
      "Flask",
      "Next.js",
      "Streamlit",
      "Playwright",
      "Postman",
    ],
  },
  {
    id: "machine-learning",
    title: "Machine Learning",
    skills: [
      "TensorFlow",
      "Keras",
      "scikit-learn",
      "Image Classification",
      "Model Training",
      "Model Development",
      "Model Evaluation",
    ],
  },
] as const satisfies readonly SkillGroup[];
